SELECT 
    COUNT(ID) AS FISH_COUNT,
    MONTH(TIME) AS MONTH    
FROM FISH_INFO
# WHERE `LENGTH` IS NOT NULL  # LENGTH 예약어라서 
GROUP BY MONTH(TIME)
HAVING COUNT(ID) > 0  -- 물고기를 잡은 기록이 있는 달만 출력
ORDER BY MONTH(TIME)